package sim.app.horde.scenarios.pioneer.vision;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface blobConstants {
    public final static int CAM_NUMBER = blobJNI.CAM_NUMBER_get();
    public final static String ORIGINAL_FRAME = blobJNI.ORIGINAL_FRAME_get();
    public final static String TRACKING_FRAME = blobJNI.TRACKING_FRAME_get();
    }
