/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sim.app.horde.scenarios.robocup2012;

public interface RCB4Constants {
    public final static int RCB4_MOT_BOW = 0;
    public final static int RCB4_MOT_HOME = 1;
    public final static int RCB4_MOT_FREE = 2;
    public final static int RCB4_MOT_HOLD = 3;
    public final static int RCB4_MOT_WAVE = 4;
    public final static int RCB4_MOT_GETUPFRONT = 5;
    public final static int RCB4_MOT_GETUPBACK = 6;
    public final static int RCB4_MOT_LEFT_KICK = 16;
    public final static int RCB4_MOT_RIGHT_KICK = 18;
    public final static int RCB4_MOT_WALK_ONE_STEP = 19;
    public final static int RCB4_MOT_LEFT_SIDE_KICK = 20;
    public final static int RCB4_MOT_RIGHT_SIDE_KICK = 21;
    public final static int RCB4_MOT_GOAL_BLOCK = 26;
    public final static int RCB4_MOT_PIVOT_OUT_LEFT = 30;
    public final static int RCB4_MOT_PIVOT_OUT_RIGHT = 31;
    public final static int RCB4_MOT_PIVOT_LEFT = 39;
    public final static int RCB4_MOT_PIVOT_RIGHT = 40;
    public final static int RCB4_MOT_FLIP_AND_GETUP = 46;
    public final static int RCB4_MOT_CALIBRATE_HOME = 47;
    public final static int RCB4_MOT_CALIBRATE = 49;
    public final static int RCB4_MOT_FORWARD_BUTTON = 33;
    public final static int RCB4_MOT_BACKWARD_BUTTON = 34;
    public final static int RCB4_MOT_LEFT_STEP_BUTTON = 35;
    public final static int RCB4_MOT_RIGHT_STEP_BUTTON = 36;
    public final static int RCB4_MOT_LEFT_TURN_BUTTON = 37;
    public final static int RCB4_MOT_RIGHT_TURN_BUTTON = 38;
    public final static int FORWARD_BUTTON = 1;
    public final static int BACKWARD_BUTTON = 2;
    public final static int LEFT_STEP_BUTTON = 8;
    public final static int RIGHT_STEP_BUTTON = 4;
    public final static int LEFT_TURN_BUTTON = 256;
    public final static int RIGHT_TURN_BUTTON = 64;
    }
